[package]
name = "Cluster"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
eframe = "0.33.3"
egui = "0.33.3"
egui_commonmark = "0.22.0"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
